on:
  workflow_dispatch:


jobs:

  create_gantt_chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository

      - name: Traverse to scripts folder
        run: |
          cd scripts

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements. txt

      - name: Create gantt chart
        run: |
          python main.py
        
      - name: Commit changes
        run: |
          git add .
          git commit -m "Save gantt chart file"
          git push