on:
  workflow_dispatch:


jobs:

  create_gantt_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Setup venv, install requirements, and run script
        run: |
          cd scripts
          sudo python -m venv my_venv
          sudo source my_venv/bin/activate
          sudo python -m pip install --upgrade pip setuptools wheel
          sudo pip install -r requirements.txt
          python main.py

      - name: Commit changes
        run: |
          git add .
          git commit -m "Save gantt chart file"
          git push