on:
  workflow_dispatch:

  schedule:
  - cron: "15 9 1 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: KarstnAncheta/my-js-action@v2
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip

    - name: Say hello to the world
      run: |
        python main.py
