on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 25,L 9 *'

jobs:

  create_gantt_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Setup venv, install requirements, and run script
        run: |
          cd scripts
          python -m venv my_venv
          source my_venv/bin/activate
          sudo python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed files