on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 15 1 *'
    - cron: '0 9 15 2 *'
    - cron: '0 9 15 3 *'
    - cron: '0 9 15 4 *'
    - cron: '0 9 15 5 *'
    - cron: '0 9 15 6 *'
    - cron: '0 9 15 7 *'
    - cron: '0 9 15 8 *'
    - cron: '0 9 15 9 *'
    - cron: '0 9 15 10 *'
    - cron: '0 9 15 11 *'
    - cron: '0 9 15 12 *'
    - cron: '0 9 31 1 *'
    - cron: '0 9 28 2 *'
    - cron: '0 9 31 3 *'
    - cron: '0 9 30 4 *'
    - cron: '0 9 31 5 *'
    - cron: '0 9 30 6 *'
    - cron: '0 9 31 7 *'
    - cron: '0 9 31 8 *'
    - cron: '0 9 30 9 *'
    - cron: '0 9 31 10 *'
    - cron: '0 9 30 11 *'
    - cron: '0 9 31 12 *'

jobs:

  create_gantt_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Setup venv, install requirements, and run script
        run: |
          cd scripts
          python -m venv my_venv
          source my_venv/bin/activate
          sudo python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed files
