on:
  workflow_dispatch:


jobs:

  create_gantt_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Traverse to scripts folder and install dependencies
        run: |
          cd scripts \
          sudo python -m pip install --upgrade pip \
          sudo pip install -r requirements. txt

      - name: Create gantt chart
        run: |
          python main.py
        
      - name: Commit changes
        run: |
          git add . \
          git commit -m "Save gantt chart file" \
          git push