on:
  schedule:
  - cron: "16 16 * * *"

jobs:

  job1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip

    - name: Say hello to the world
      run: |
        python main.py
    
  job2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip

    - name: Other job
      run: |
        python other.py
    
